// Free API Registry — seed records.
//
// Statuses are HONEST at seed time:
//   active        → endpoint verified reachable from this app (or already
//                   integrated as a venue adapter) and keyless
//   disabled      → free tier exists but requires an API key that is not
//                   configured; the note says which env var unlocks it
//   manual_review → no permitted structured API found (e.g. congressional
//                   financial disclosures ship as PDFs behind a search UI —
//                   we will NOT scrape them)
//   unavailable   → no permitted source exists for the category at all
//
// `lastTermsReview` is stamped when the registry is (re)seeded; the terms
// summary in allowedUse/prohibitedUse is a good-faith reading, not legal
// advice, and sources flip to manual_review when terms change.

import type { SourceRecord } from "./types";

type Seed = Omit<
  SourceRecord,
  "reliabilityScore" | "lastSuccessfulCall" | "lastFailedCall" | "lastTermsReview"
>;

const S = (s: Seed): Seed => s;

export const SOURCE_SEEDS: Seed[] = [
  // ── Prediction markets ─────────────────────────────────────────────────────
  S({
    sourceId: "polymarket_gamma", sourceName: "Polymarket Gamma API",
    category: "prediction_markets", baseUrl: "https://gamma-api.polymarket.com",
    docsUrl: "https://docs.polymarket.com", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public; be conservative (app: ≤1 req/15s cached)",
    updateFrequency: "seconds", historicalDepth: "full market metadata",
    allowedUse: "public market metadata and prices for analytics",
    prohibitedUse: "no bulk redistribution as a competing feed",
    commercialUseAllowed: "unknown", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["all"], marketCategoriesSupported: ["all"],
    status: "active", healthPath: "/events?limit=1",
  }),
  S({
    sourceId: "polymarket_data", sourceName: "Polymarket Data API",
    category: "prediction_markets", baseUrl: "https://data-api.polymarket.com",
    docsUrl: "https://docs.polymarket.com", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public; app caps wallet refresh at ~1 req/s bursts",
    updateFrequency: "seconds", historicalDepth: "trades/positions per wallet & market",
    allowedUse: "public trades, positions, holders for analytics (wallets are public on-chain actors)",
    prohibitedUse: "no deanonymization, no harassment, no identity inference",
    commercialUseAllowed: "unknown", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["wallet_shadow", "wallet_fade", "flow"],
    marketCategoriesSupported: ["all"], status: "active", healthPath: "/trades?limit=1",
  }),
  S({
    sourceId: "polymarket_clob", sourceName: "Polymarket CLOB read endpoints",
    category: "prediction_markets", baseUrl: "https://clob.polymarket.com",
    docsUrl: "https://docs.polymarket.com", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public read; books cached 8s in-app",
    updateFrequency: "real-time", historicalDepth: "prices-history per token",
    allowedUse: "order books, price history for analytics and execution preview",
    commercialUseAllowed: "unknown", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["all"], marketCategoriesSupported: ["all"],
    status: "active", healthPath: "/ok",
  }),
  S({
    sourceId: "kalshi_public", sourceName: "Kalshi public market data",
    category: "prediction_markets", baseUrl: "https://api.elections.kalshi.com/trade-api/v2",
    docsUrl: "https://trading-api.readme.io", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public tier; app caches 15s",
    updateFrequency: "seconds", historicalDepth: "markets, events, order books",
    allowedUse: "public market data for analytics; trading requires a Kalshi account",
    commercialUseAllowed: "conditions", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["venue_divergence", "reference_price", "ecl"],
    marketCategoriesSupported: ["all"], status: "active",
    healthPath: "/markets?limit=1",
  }),
  S({
    sourceId: "kalshi_ws", sourceName: "Kalshi WebSocket feeds",
    category: "prediction_markets", baseUrl: "wss://api.elections.kalshi.com/trade-api/ws/v2",
    docsUrl: "https://trading-api.readme.io", officialSource: true, freeAvailable: false,
    apiKeyRequired: true, apiKeyEnvVar: "KALSHI_API_KEY_ID", authenticationType: "api_key",
    rateLimit: "authenticated", updateFrequency: "real-time",
    allowedUse: "streaming market data for account holders",
    commercialUseAllowed: "conditions", redistributionAllowed: "no",
    signalCategoriesSupported: ["venue_divergence"], marketCategoriesSupported: ["all"],
    status: "disabled", note: "requires Kalshi credentials (KALSHI_API_KEY_ID/KALSHI_PRIVATE_KEY); REST polling is used instead",
  }),
  // ── Crypto ─────────────────────────────────────────────────────────────────
  S({
    sourceId: "coinbase_public", sourceName: "Coinbase Advanced Trade public market data",
    category: "crypto", baseUrl: "https://api.coinbase.com/api/v3/brokerage/market",
    docsUrl: "https://docs.cdp.coinbase.com", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "10 req/s public; app caches spot 5s, vol 10min",
    updateFrequency: "real-time", historicalDepth: "candles (350 bars/req)",
    allowedUse: "public product, book and candle data as EXECUTABLE-VENUE reference",
    commercialUseAllowed: "conditions", redistributionAllowed: "no",
    signalCategoriesSupported: ["ecl", "reference_price", "deadline_curvature"],
    marketCategoriesSupported: ["crypto"], status: "active",
    healthPath: "/products/BTC-USD",
  }),
  S({
    sourceId: "coingecko", sourceName: "CoinGecko keyless API",
    category: "crypto", baseUrl: "https://api.coingecko.com/api/v3",
    docsUrl: "https://docs.coingecko.com", officialSource: false, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "~10-30 req/min keyless; app caches 60s",
    updateFrequency: "1-5 min", historicalDepth: "years (daily)",
    allowedUse: "REFERENCE ONLY — aggregated prices; never executable, never a resolution source",
    prohibitedUse: "must not be treated as executable liquidity",
    commercialUseAllowed: "conditions", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["free_data_divergence"], marketCategoriesSupported: ["crypto"],
    status: "active", healthPath: "/ping",
  }),
  S({
    sourceId: "defillama", sourceName: "DeFiLlama public API",
    category: "crypto", baseUrl: "https://api.llama.fi",
    docsUrl: "https://defillama.com/docs/api", officialSource: false, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public; be conservative", updateFrequency: "minutes-hours",
    allowedUse: "TVL/protocol reference data where permitted",
    commercialUseAllowed: "conditions", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["free_data_divergence"], marketCategoriesSupported: ["crypto"],
    status: "disabled", note: "registered for research; no adapter shipped yet — flip to active only after a concrete feature passes DATA VALIDATION",
  }),
  S({
    sourceId: "polygon_rpc", sourceName: "Public Polygon RPC (on-chain reads)",
    category: "crypto", baseUrl: "https://polygon-rpc.com",
    officialSource: false, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "public endpoints are best-effort",
    updateFrequency: "per block (~2s)",
    allowedUse: "read-only public chain state (e.g. USDC balances of PUBLIC wallets)",
    prohibitedUse: "no deanonymization; no private data (none exists on-chain anyway)",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["wallet_shadow"], marketCategoriesSupported: ["all"],
    status: "disabled", note: "data-api already provides positions/trades; direct RPC reads are a fallback, not yet needed",
  }),
  // ── Macro ──────────────────────────────────────────────────────────────────
  S({
    sourceId: "fred", sourceName: "FRED (St. Louis Fed)",
    category: "macro", baseUrl: "https://api.stlouisfed.org/fred",
    docsUrl: "https://fred.stlouisfed.org/docs/api/fred/", officialSource: true,
    freeAvailable: true, apiKeyRequired: true, apiKeyEnvVar: "FRED_API_KEY",
    authenticationType: "api_key", rateLimit: "120 req/min with free key",
    updateFrequency: "per release", historicalDepth: "decades",
    allowedUse: "economic series + release calendar; attribution required",
    commercialUseAllowed: "conditions", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["calendar_shock", "policy_momentum"],
    marketCategoriesSupported: ["macro", "fed_rates"],
    status: "disabled", note: "free key required — set FRED_API_KEY to unlock the release-calendar feature",
  }),
  S({
    sourceId: "bls", sourceName: "BLS Public Data API",
    category: "macro", baseUrl: "https://api.bls.gov/publicAPI/v2",
    docsUrl: "https://www.bls.gov/developers/", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "25 req/day keyless; 500/day with free key (BLS_API_KEY)",
    updateFrequency: "per release (CPI, jobs)", historicalDepth: "decades",
    allowedUse: "official CPI/employment series — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["macro"],
    status: "disabled", note: "keyless tier is 25 req/day — adapter ships with the calendar-shock feature; set BLS_API_KEY for the 500/day tier",
  }),
  S({
    sourceId: "bea", sourceName: "BEA API (GDP)",
    category: "macro", baseUrl: "https://apps.bea.gov/api/data",
    docsUrl: "https://apps.bea.gov/api/", officialSource: true, freeAvailable: true,
    apiKeyRequired: true, apiKeyEnvVar: "BEA_API_KEY", authenticationType: "api_key",
    rateLimit: "free key; generous", updateFrequency: "per release",
    allowedUse: "official GDP/NIPA data — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["macro"],
    status: "disabled", note: "free key required (BEA_API_KEY)",
  }),
  S({
    sourceId: "census", sourceName: "U.S. Census APIs",
    category: "macro", baseUrl: "https://api.census.gov/data",
    docsUrl: "https://www.census.gov/data/developers.html", officialSource: true,
    freeAvailable: true, apiKeyRequired: false, authenticationType: "none",
    rateLimit: "500 req/day keyless; free key removes cap",
    updateFrequency: "per release", allowedUse: "official statistics — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["policy_momentum"], marketCategoriesSupported: ["macro"],
    status: "disabled", note: "no live feature maps to census data yet — idea stage",
  }),
  S({
    sourceId: "treasury_fiscal", sourceName: "Treasury Fiscal Data API",
    category: "macro", baseUrl: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service",
    docsUrl: "https://fiscaldata.treasury.gov/api-documentation/", officialSource: true,
    freeAvailable: true, apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public, generous", updateFrequency: "daily",
    allowedUse: "debt/deficit/auction data — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["policy_momentum"], marketCategoriesSupported: ["macro"],
    status: "active", healthPath: "/v2/accounting/od/debt_to_penny?page[size]=1",
  }),
  S({
    sourceId: "eia", sourceName: "EIA energy data",
    category: "macro", baseUrl: "https://api.eia.gov/v2",
    docsUrl: "https://www.eia.gov/opendata/", officialSource: true, freeAvailable: true,
    apiKeyRequired: true, apiKeyEnvVar: "EIA_API_KEY", authenticationType: "api_key",
    rateLimit: "free key", updateFrequency: "weekly (oil inventories)",
    allowedUse: "official energy statistics — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["macro"],
    status: "disabled", note: "free key required (EIA_API_KEY)",
  }),
  S({
    sourceId: "sec_edgar", sourceName: "SEC EDGAR APIs",
    category: "macro", baseUrl: "https://data.sec.gov",
    docsUrl: "https://www.sec.gov/edgar/sec-api-documentation", officialSource: true,
    freeAvailable: true, apiKeyRequired: false, authenticationType: "user_agent",
    rateLimit: "10 req/s with declared User-Agent — hard requirement",
    updateFrequency: "real-time filings", historicalDepth: "full filing history",
    allowedUse: "official filings; fair-access rules require a declared UA and rate discipline",
    prohibitedUse: "no anonymous bulk scraping",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["disclosure_radar", "policy_momentum"],
    marketCategoriesSupported: ["macro", "ai_tech"],
    status: "disabled", note: "registered; filing-feed feature is idea-stage (needs a concrete market mapping first)",
  }),
  // ── Politics & regulation ─────────────────────────────────────────────────
  S({
    sourceId: "federal_register", sourceName: "Federal Register API",
    category: "politics_regulation", baseUrl: "https://www.federalregister.gov/api/v1",
    docsUrl: "https://www.federalregister.gov/developers/documentation/api/v1",
    officialSource: true, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "public, generous; app caches 6h",
    updateFrequency: "daily (publication cycle)", historicalDepth: "1994+",
    allowedUse: "official rulemaking documents — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["disclosure_radar", "policy_momentum"],
    marketCategoriesSupported: ["politics", "macro", "crypto", "courts"],
    status: "active", healthPath: "/documents.json?per_page=1",
  }),
  S({
    sourceId: "congress_gov", sourceName: "Congress.gov API",
    category: "politics_regulation", baseUrl: "https://api.congress.gov/v3",
    docsUrl: "https://api.congress.gov/", officialSource: true, freeAvailable: true,
    apiKeyRequired: true, apiKeyEnvVar: "CONGRESS_GOV_API_KEY",
    authenticationType: "api_key", rateLimit: "5,000 req/hr with free key",
    updateFrequency: "hours", allowedUse: "bills, actions, hearings — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["policy_momentum", "disclosure_radar"],
    marketCategoriesSupported: ["politics", "elections"],
    status: "disabled", note: "free key required (CONGRESS_GOV_API_KEY) — adapter ships once configured; no scraping fallback",
  }),
  S({
    sourceId: "regulations_gov", sourceName: "Regulations.gov API",
    category: "politics_regulation", baseUrl: "https://api.regulations.gov/v4",
    docsUrl: "https://open.gsa.gov/api/regulationsgov/", officialSource: true,
    freeAvailable: true, apiKeyRequired: true, apiKeyEnvVar: "REGULATIONS_GOV_API_KEY",
    authenticationType: "api_key", rateLimit: "free key via api.data.gov",
    updateFrequency: "daily", allowedUse: "dockets/comments — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["policy_momentum"], marketCategoriesSupported: ["politics"],
    status: "disabled", note: "free key required (REGULATIONS_GOV_API_KEY)",
  }),
  S({
    sourceId: "house_disclosures", sourceName: "House financial disclosures",
    category: "politics_regulation", baseUrl: "https://disclosures-clerk.house.gov",
    officialSource: true, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "n/a",
    updateFrequency: "per filing (up to 45-day legal lag)",
    allowedUse: "public disclosures — but published as PDFs behind a search UI, no structured API",
    prohibitedUse: "we do not scrape the search UI",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["disclosure_radar"], marketCategoriesSupported: ["politics"],
    status: "manual_review",
    note: "no official structured API; annual bulk XML/ZIP exists for periodic reports. Treated as DELAYED context only — never real-time. Integration deferred until a permitted structured path is validated.",
  }),
  S({
    sourceId: "senate_disclosures", sourceName: "Senate financial disclosures (eFD)",
    category: "politics_regulation", baseUrl: "https://efdsearch.senate.gov",
    officialSource: true, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "n/a",
    updateFrequency: "per filing (up to 45-day legal lag)",
    allowedUse: "public disclosures behind a search UI with terms acknowledgment — no structured API",
    prohibitedUse: "we do not script past the acknowledgment gate",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["disclosure_radar"], marketCategoriesSupported: ["politics"],
    status: "manual_review",
    note: "eFD requires an interactive terms acknowledgment; scripting past it would violate site terms. Deferred.",
  }),
  S({
    sourceId: "openfec", sourceName: "OpenFEC API",
    category: "politics_regulation", baseUrl: "https://api.open.fec.gov/v1",
    docsUrl: "https://api.open.fec.gov/developers/", officialSource: true,
    freeAvailable: true, apiKeyRequired: true, apiKeyEnvVar: "OPENFEC_API_KEY",
    authenticationType: "api_key", rateLimit: "free key via api.data.gov",
    updateFrequency: "daily", allowedUse: "campaign finance — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["policy_momentum"], marketCategoriesSupported: ["elections"],
    status: "disabled", note: "free key required (OPENFEC_API_KEY); election-finance feature is idea-stage",
  }),
  S({
    sourceId: "usaspending", sourceName: "USAspending (government contracts)",
    category: "politics_regulation", baseUrl: "https://api.usaspending.gov/api/v2",
    docsUrl: "https://api.usaspending.gov/", officialSource: true, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "public, generous", updateFrequency: "daily",
    allowedUse: "contract awards — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["policy_momentum"], marketCategoriesSupported: ["politics"],
    status: "active", healthPath: "/references/agency/456/",
  }),
  // ── Weather & climate ─────────────────────────────────────────────────────
  S({
    sourceId: "nws", sourceName: "National Weather Service API",
    category: "weather_climate", baseUrl: "https://api.weather.gov",
    docsUrl: "https://www.weather.gov/documentation/services-web-api",
    officialSource: true, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "user_agent", rateLimit: "generous with declared User-Agent",
    updateFrequency: "minutes (alerts)", allowedUse: "official forecasts/alerts — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["weather"],
    status: "active", healthPath: "/alerts/active?area=FL",
  }),
  S({
    sourceId: "open_meteo", sourceName: "Open-Meteo",
    category: "weather_climate", baseUrl: "https://api.open-meteo.com/v1",
    docsUrl: "https://open-meteo.com/en/docs", officialSource: false, freeAvailable: true,
    apiKeyRequired: false, authenticationType: "none",
    rateLimit: "10k req/day free non-commercial", updateFrequency: "hourly",
    allowedUse: "forecast reference — non-commercial free tier",
    commercialUseAllowed: "conditions", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["weather"],
    status: "disabled", note: "NWS is the preferred official source; Open-Meteo registered as fallback",
  }),
  S({
    sourceId: "nhc", sourceName: "National Hurricane Center feeds",
    category: "weather_climate", baseUrl: "https://www.nhc.noaa.gov",
    officialSource: true, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "public RSS/GIS feeds",
    updateFrequency: "advisory cycle (6h, faster in storms)",
    allowedUse: "official advisories — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["weather"],
    status: "disabled", note: "hurricane-market feature is idea-stage (seasonal)",
  }),
  // ── News & event flow ─────────────────────────────────────────────────────
  S({
    sourceId: "gdelt", sourceName: "GDELT 2.0 DOC API",
    category: "news_events", baseUrl: "https://api.gdeltproject.org/api/v2",
    docsUrl: "https://blog.gdeltproject.org/gdelt-doc-2-0-api-debuts/",
    officialSource: false, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "public; be conservative",
    updateFrequency: "15 min", historicalDepth: "rolling 3 months (doc API)",
    allowedUse: "news volume/timeline metadata for attention measurement",
    commercialUseAllowed: "conditions", redistributionAllowed: "conditions",
    signalCategoriesSupported: ["attention_imbalance"], marketCategoriesSupported: ["all"],
    status: "disabled",
    note: "adapter ships throttle-safe (ONE topic per 6h, rotating): GDELT holds shared-egress IPs in cooldowns far beyond the documented 1/5s. Flips to active on first successful ingest; attention_imbalance advances only then.",
  }),
  S({
    sourceId: "fed_calendar", sourceName: "Federal Reserve releases & FOMC calendar",
    category: "news_events", baseUrl: "https://www.federalreserve.gov",
    officialSource: true, freeAvailable: true, apiKeyRequired: false,
    authenticationType: "none", rateLimit: "public pages/RSS",
    updateFrequency: "per meeting/release", allowedUse: "official calendar — public domain",
    commercialUseAllowed: "yes", redistributionAllowed: "yes",
    signalCategoriesSupported: ["calendar_shock"], marketCategoriesSupported: ["fed_rates"],
    status: "manual_review", note: "calendar is HTML/RSS, not a JSON API — needs a validated parser before any feature relies on it",
  }),
  // ── Sports ────────────────────────────────────────────────────────────────
  S({
    sourceId: "sports_official", sourceName: "Official league data",
    category: "sports", baseUrl: "",
    officialSource: true, freeAvailable: false, apiKeyRequired: true,
    authenticationType: "api_key", rateLimit: "n/a", updateFrequency: "n/a",
    allowedUse: "only official or sanctioned feeds would be permitted",
    prohibitedUse: "no scraping of private/prohibited feeds — hard rule",
    commercialUseAllowed: "no", redistributionAllowed: "no",
    signalCategoriesSupported: [], marketCategoriesSupported: ["sports"],
    status: "unavailable",
    note: "no permitted free source exists; sports data is marked unavailable rather than scraped",
  }),
];

/** stamp seed-time review + neutral reliability into full records */
export function seedSourceRecords(now: number): SourceRecord[] {
  return SOURCE_SEEDS.map((s) => ({
    ...s,
    reliabilityScore: s.status === "active" ? 0.8 : 0.5,
    lastTermsReview: now,
  }));
}
